import { useState } from "react";
import { FaClock, FaEnvelope, FaLifeRing, FaComments, FaShieldAlt, FaVideo } from "react-icons/fa";
import { api } from "../lib/api";

const emptyForm = { name: "", email: "", phone: "", city: "", service: "Online coaching question", message: "" };

export default function Contact() {
  const [form, setForm] = useState(emptyForm);
  const [status, setStatus] = useState("");
  const update = (field, value) => setForm((current) => ({ ...current, [field]: value }));
  const submit = async (event) => { event.preventDefault(); setStatus("Sending..."); try { await api.post("/tickets", { subject: `${form.service} from ${form.name}`, ...form, source: "website-contact" }); setForm(emptyForm); setStatus("Thanks — your message was sent. Please allow 1–3 business days for a response."); } catch (error) { setStatus(error.message || "Could not send your request right now."); } };

  return <div className="pp-page min-h-screen px-6 pt-28 pb-16"><div className="mx-auto max-w-7xl">
    <section className="overflow-hidden rounded-[2rem] bg-[#12372a] p-8 text-white shadow-xl md:p-10"><div className="grid gap-8 lg:grid-cols-[1fr_.65fr] lg:items-end"><div><p className="text-xs font-black uppercase tracking-[.22em] text-[#c6ff4a]">Contact GOOD Coaching</p><h1 className="mt-3 max-w-3xl text-4xl font-black text-white md:text-6xl">How can we help?</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-white/80">Get help with accounts, coach profiles, personalized requests, payments, or video submissions.</p></div><div className="grid grid-cols-2 gap-3"><Quick icon={<FaClock/>} title="Response time" text="1–3 business days"/><Quick icon={<FaComments/>} title="Coach requests" text="Use profile chat"/></div></div></section>
    <section className="mt-8 grid gap-6 lg:grid-cols-[1fr_.42fr]"><form onSubmit={submit} className="rounded-[2rem] border border-[#12372a]/10 bg-white p-6 shadow-xl md:p-8"><div className="mb-6"><h2 className="text-2xl font-black text-[#12372a]">Send support a message</h2><p className="mt-1 text-sm text-[#40584f]">For a personalized coaching quote, open a coach profile and choose Personalized Request.</p></div><div className="grid gap-4 md:grid-cols-2"><Field label="Name"><input value={form.name} onChange={(e) => update("name", e.target.value)} className="pp-input mt-1 px-4 py-3" required /></Field><Field label="Email"><input value={form.email} onChange={(e) => update("email", e.target.value)} type="email" className="pp-input mt-1 px-4 py-3" required /></Field><Field label="Phone"><input value={form.phone} onChange={(e) => update("phone", e.target.value)} type="tel" className="pp-input mt-1 px-4 py-3" /></Field><Field label="City, state, country"><input value={form.city} onChange={(e) => update("city", e.target.value)} className="pp-input mt-1 px-4 py-3" /></Field><Field label="What do you need help with?" wide><select value={form.service} onChange={(e) => update("service", e.target.value)} className="pp-input mt-1 px-4 py-3"><option>Online coaching question</option><option>Video upload support</option><option>Coach application question</option><option>Account access question</option><option>Payment or quote question</option><option>DUPR profile question</option></select></Field><Field label="Message" wide><textarea value={form.message} onChange={(e) => update("message", e.target.value)} rows={7} className="pp-input mt-1 px-4 py-3" required placeholder="Include the page you were using and what you expected to happen." /></Field></div><button type="submit" className="pp-btn-primary mt-5 w-full px-6 py-4"><FaEnvelope className="mr-2"/>Send support message</button>{status && <p className="mt-4 rounded-2xl bg-[#eaf9f7] p-4 text-sm font-bold text-[#205746]">{status}</p>}</form>
      <aside className="space-y-5"><div className="rounded-[2rem] border border-[#12372a]/10 bg-white p-6 shadow-lg"><FaLifeRing className="text-3xl text-[#087f73]"/><h2 className="mt-4 text-xl font-black text-[#12372a]">Helpful reminders</h2><div className="mt-5 space-y-4"><Reminder icon={<FaVideo/>} text="Customer videos are limited to 15 minutes."/><Reminder icon={<FaClock/>} text="Allow 1–3 business days for coach responses."/><Reminder icon={<FaShieldAlt/>} text="Only approve and pay quotes you understand."/><Reminder icon={<FaEnvelope/>} text="Keep your account email current for replies."/></div></div><div className="rounded-[2rem] bg-[#fff1c7] p-6"><h3 className="font-black text-[#12372a]">Need a custom training plan?</h3><p className="mt-2 text-sm leading-6 text-[#40584f]">Choose a coach, select multiple services in Personalized Request, and discuss the final quote in chat.</p><a href="/coaches" className="pp-btn-secondary mt-4 px-4 py-2 text-sm">Browse coaches</a></div></aside>
    </section>
  </div></div>;
}
function Field({ label, wide, children }) { return <label className={wide ? "block md:col-span-2" : "block"}><span className="text-sm font-black text-[#29483d]">{label}</span>{children}</label>; }
function Quick({ icon, title, text }) { return <div className="rounded-2xl bg-white/10 p-4"><div className="text-[#c6ff4a]">{icon}</div><div className="mt-2 text-sm font-black text-white">{title}</div><div className="text-xs text-white/70">{text}</div></div>; }
function Reminder({ icon, text }) { return <div className="flex gap-3 text-sm font-semibold leading-6 text-[#40584f]"><span className="mt-1 text-[#087f73]">{icon}</span>{text}</div>; }
