import { useEffect, useMemo, useState } from "react";
import { FaComments, FaEnvelope, FaPaperPlane, FaReceipt } from "react-icons/fa";
import { api } from "../lib/api";
import { useAuth } from "../context/AuthContext";
import { useToast } from "../components/Toast";

export default function Messages() {
  const { token, user } = useAuth();
  const { push } = useToast();
  const [rows, setRows] = useState([]); const [selected, setSelected] = useState(null); const [message, setMessage] = useState("");
  const [quote, setQuote] = useState({ amount: "", discountPercent: 0, scope: "", paymentUrl: "" });
  const load = async () => { const data = await api.get("/inquiries/my", token); setRows(data || []); setSelected((current) => data?.find((x) => x._id === current?._id) || data?.[0] || null); };
  useEffect(() => { load().catch((e) => push(e.message, "error")); }, [token]);
  const isCoach = useMemo(() => selected && String(selected.coachId?.userId?._id || selected.coachId?.userId) === String(user?._id || user?.id), [selected, user]);
  const send = async () => { if (!message.trim() || !selected) return; const row = await api.post(`/inquiries/${selected._id}/messages`, { message }, token); setSelected(row); setMessage(""); load(); };
  const sendQuote = async () => { const row = await api.post(`/inquiries/${selected._id}/quote`, quote, token); setSelected(row); push("Quote sent for customer approval.", "success"); load(); };
  const approve = async () => { const result = await api.post(`/inquiries/${selected._id}/quote/approve`, {}, token); setSelected(result.inquiry); push(result.paymentNextStep, "success"); load(); };
  return <div className="pp-page min-h-screen px-6 pt-32 pb-16"><div className="mx-auto max-w-7xl">
    <div className="mb-6"><p className="font-black uppercase tracking-[.2em] text-[#087f73]">Before you purchase</p><h1 className="mt-2 text-4xl font-black text-[#12372a]">Coach conversations & custom quotes</h1><p className="mt-2 text-[#5f746c]">Discuss goals, confirm scope, and approve any expanded quote before payment.</p></div>
    <div className="grid gap-5 lg:grid-cols-[.72fr_1.28fr]"><aside className="pp-card rounded-3xl p-4"><h2 className="mb-3 font-black text-[#12372a]"><FaComments className="mr-2 inline"/>Conversations</h2>{rows.length ? rows.map((r)=><button key={r._id} onClick={()=>setSelected(r)} className={`mb-2 w-full rounded-2xl border p-4 text-left ${selected?._id===r._id?'border-[#00a896] bg-[#d9f7fb]':'border-[#12372a]/10 bg-white'}`}><b className="text-[#12372a]">{isCoach ? r.playerId?.fullName : r.coachId?.displayName}</b><div className="text-sm text-[#5f746c]">{r.subject} • {r.status}</div></button>):<p className="text-sm text-[#5f746c]">Start a conversation from a coach profile.</p>}</aside>
    <main className="pp-card rounded-3xl p-5">{selected ? <><div className="flex flex-wrap justify-between gap-3 border-b border-[#12372a]/10 pb-4"><div><h2 className="text-2xl font-black text-[#12372a]">{selected.subject}</h2><span className="text-sm font-bold text-[#087f73]">{selected.coachId?.presenceStatus === 'online' ? '● Online now' : '○ Offline — replies asynchronously'}</span></div>{selected.coachId?.contactEmail && <a href={`mailto:${selected.coachId.contactEmail}`} className="pp-btn-secondary px-4 py-2"><FaEnvelope className="mr-2"/>Email coach</a>}</div>
    <div className="my-5 max-h-80 space-y-3 overflow-auto">{selected.messages?.map((m)=><div key={m._id} className={`rounded-2xl p-4 ${String(m.senderId)===String(user?._id||user?.id)?'ml-10 bg-[#d9f7fb]':'mr-10 bg-[#fff8e7]'}`}><p className="whitespace-pre-wrap text-sm text-[#12372a]">{m.body}</p></div>)}</div>
    <div className="flex gap-2"><textarea value={message} onChange={(e)=>setMessage(e.target.value)} rows={2} className="pp-input px-4 py-3" placeholder="Ask about goals, deliverables, timing, or scope..."/><button onClick={send} className="pp-btn-primary px-5"><FaPaperPlane/></button></div>
    {selected.quote?.status && selected.quote.status !== 'draft' && <div className="mt-5 rounded-2xl border border-[#00a896]/30 bg-[#d9f7fb] p-4 text-[#12372a]"><b><FaReceipt className="mr-2 inline"/>Custom quote: ${Number(selected.quote.amount||0).toFixed(2)}</b>{selected.quote.discountPercent>0&&<span> • {selected.quote.discountPercent}% package discount</span>}<p className="mt-2 whitespace-pre-wrap text-sm">{selected.quote.scope}</p>{!isCoach&&selected.quote.status==='sent'&&<button onClick={approve} className="pp-btn-primary mt-3 px-4 py-2">Approve quote & continue to payment</button>}{selected.quote.status === 'approved' && selected.quote.paymentUrl && <a href={selected.quote.paymentUrl} target="_blank" rel="noreferrer" className="pp-btn-primary mt-3 px-4 py-2">Pay approved quote</a>}<div className="mt-2 text-xs font-bold uppercase">Status: {selected.quote.status}</div></div>}
    {isCoach && <div className="mt-5 rounded-2xl border border-[#12372a]/10 bg-white p-4"><h3 className="font-black text-[#12372a]">Send or revise a custom quote</h3><div className="mt-3 grid gap-3 md:grid-cols-2"><input className="pp-input px-4 py-3" type="number" min="0" value={quote.amount} onChange={(e)=>setQuote(q=>({...q,amount:e.target.value}))} placeholder="Quote amount"/><input className="pp-input px-4 py-3" type="number" min="0" max="100" value={quote.discountPercent} onChange={(e)=>setQuote(q=>({...q,discountPercent:e.target.value}))} placeholder="Package discount %"/><input className="pp-input px-4 py-3 md:col-span-2" value={quote.paymentUrl} onChange={(e)=>setQuote(q=>({...q,paymentUrl:e.target.value}))} placeholder="Optional secure payment URL"/><textarea className="pp-input px-4 py-3 md:col-span-2" rows={3} value={quote.scope} onChange={(e)=>setQuote(q=>({...q,scope:e.target.value}))} placeholder="Final scope, deliverables, and anything beyond the original request"/></div><button onClick={sendQuote} className="pp-btn-primary mt-3 px-4 py-2">Send quote for approval</button></div>}</>:<div className="py-20 text-center text-[#5f746c]">Select a conversation.</div>}</main></div>
  </div></div>;
}
